<?php
/**
 * Template Name: Policies Page
 *
 * @package Tattva_Dental
 */

get_header();
?>

<div class="page-header">
    <div class="container">
        <h1>Policies</h1>
        <p>Terms & Conditions, Privacy Policy, and Refund Policy</p>
    </div>
</div>

<section class="section">
    <div class="container">
        <!-- Policy Navigation -->
        <div style="display: flex; gap: 1rem; margin-bottom: 2rem; flex-wrap: wrap; justify-content: center;">
            <a href="#terms" class="btn btn-outline" style="padding: 0.75rem 1.5rem;">Terms & Conditions</a>
            <a href="#privacy" class="btn btn-outline" style="padding: 0.75rem 1.5rem;">Privacy Policy</a>
            <a href="#refund" class="btn btn-outline" style="padding: 0.75rem 1.5rem;">Refund Policy</a>
        </div>
        
        <!-- Terms & Conditions -->
        <div id="terms" class="policy-section" style="background: var(--color-surface-light); border-radius: var(--radius-md); padding: 2rem; margin-bottom: 2rem; border: 1px solid var(--color-surface-lighter);">
            <h2 style="color: var(--color-primary); margin-bottom: 1.5rem;">Terms & Conditions</h2>
            
            <div style="color: var(--color-text); line-height: 1.8;">
                <p>This document is an electronic record in terms of Information Technology Act, 2000 and rules there under as applicable and the amended provisions pertaining to electronic records in various statutes as amended by the Information Technology Act, 2000. This electronic record is generated by a computer system and does not require any physical or digital signatures.</p>
                
                <p>This document is published in accordance with the provisions of Rule 3 (1) of the Information Technology (Intermediaries guidelines) Rules, 2011 that require publishing the rules and regulations, privacy policy and Terms of Use for access or usage of domain name <strong><?php echo esc_url(home_url('/')); ?></strong> ('Website'), including the related mobile site and mobile application (hereinafter referred to as 'Platform').</p>
                
                <p>The Platform is owned by <strong>Tattva Dental Clinic</strong>, with its registered office at <strong><?php echo esc_html(get_theme_mod('tattva_address', 'Tattva Dental Clinic, Uppal, Hyderabad, Telangana 500039, India')); ?></strong> (hereinafter referred to as 'Platform Owner', 'we', 'us', 'our').</p>
                
                <p>Your use of the Platform and services and tools are governed by the following terms and conditions ("Terms of Use") as applicable to the Platform including the applicable policies which are incorporated herein by way of reference. If You transact on the Platform, You shall be subject to the policies that are applicable to the Platform for such transaction. By mere use of the Platform, You shall be contracting with the Platform Owner and these terms and conditions including the policies constitute Your binding obligations, with Platform Owner.</p>
                
                <p>These Terms of Use relate to your use of our website, goods (as applicable) or services (as applicable) (collectively, 'Services'). Any terms and conditions proposed by You which are in addition to or which conflict with these Terms of Use are expressly rejected by the Platform Owner and shall be of no force or effect. These Terms of Use can be modified at any time without assigning any reason. It is your responsibility to periodically review these Terms of Use to stay informed of updates.</p>
                
                <p>For the purpose of these Terms of Use, wherever the context so requires 'you', 'your' or 'user' shall mean any natural or legal person who has agreed to become a user/buyer on the Platform.</p>
                
                <p><strong>ACCESSING, BROWSING OR OTHERWISE USING THE PLATFORM INDICATES YOUR AGREEMENT TO ALL THE TERMS AND CONDITIONS UNDER THESE TERMS OF USE, SO PLEASE READ THE TERMS OF USE CAREFULLY BEFORE PROCEEDING.</strong></p>
                
                <h3 style="color: var(--color-white); margin: 1.5rem 0 1rem;">Use of Platform</h3>
                <p>The use of Platform and/or availing of our Services is subject to the following Terms of Use:</p>
                
                <ul style="margin-left: 1.5rem; margin-bottom: 1rem;">
                    <li style="margin-bottom: 0.75rem;">To access and use the Services, you agree to provide true, accurate and complete information to us during and after registration, and you shall be responsible for all acts done through the use of your registered account on the Platform.</li>
                    
                    <li style="margin-bottom: 0.75rem;">Neither we nor any third parties provide any warranty or guarantee as to the accuracy, timeliness, performance, completeness or suitability of the information and materials offered on this website or through the Services, for any specific purpose. You acknowledge that such information and materials may contain inaccuracies or errors and we expressly exclude liability for any such inaccuracies or errors to the fullest extent permitted by law.</li>
                    
                    <li style="margin-bottom: 0.75rem;">Your use of our Services and the Platform is solely and entirely at your own risk and discretion for which we shall not be liable to you in any manner. You are required to independently assess and ensure that the Services meet your requirements.</li>
                    
                    <li style="margin-bottom: 0.75rem;">The contents of the Platform and the Services are proprietary to us and are licensed to us. You will not have any authority to claim any intellectual property rights, title, or interest in its contents. The contents includes and is not limited to the design, layout, look and graphics.</li>
                    
                    <li style="margin-bottom: 0.75rem;">You acknowledge that unauthorized use of the Platform and/or the Services may lead to action against you as per these Terms of Use and/or applicable laws.</li>
                    
                    <li style="margin-bottom: 0.75rem;">You agree to pay us the charges associated with availing the Services.</li>
                    
                    <li style="margin-bottom: 0.75rem;">You agree not to use the Platform and/or Services for any purpose that is unlawful, illegal or forbidden by these Terms, or Indian or local laws that might apply to you.</li>
                    
                    <li style="margin-bottom: 0.75rem;">You agree and acknowledge that website and the Services may contain links to other third party websites. On accessing these links, you will be governed by the terms of use, privacy policy and such other policies of such third party websites. These links are provided for your convenience for provide further information.</li>
                    
                    <li style="margin-bottom: 0.75rem;">You understand that upon initiating a transaction for availing the Services you are entering into a legally binding and enforceable contract with the Platform Owner for the Services.</li>
                    
                    <li style="margin-bottom: 0.75rem;">You shall indemnify and hold harmless Platform Owner, its affiliates, group companies (as applicable) and their respective officers, directors, agents, and employees, from any claim or demand, or actions including reasonable attorney's fees, made by any third party or penalty imposed due to or arising out of Your breach of this Terms of Use, privacy Policy and other Policies, or Your violation of any law, rules or regulations or the rights (including infringement of intellectual property rights) of a third party.</li>
                </ul>
                
                <h3 style="color: var(--color-white); margin: 1.5rem 0 1rem;">Governing Law & Jurisdiction</h3>
                <p>Notwithstanding anything contained in these Terms of Use, the parties shall not be liable for any failure to perform an obligation under these Terms if performance is prevented or delayed by a force majeure event.</p>
                
                <p>These Terms and any dispute or claim relating to it, or its enforceability, shall be governed by and construed in accordance with the laws of India.</p>
                
                <p>All disputes arising out of or in connection with these Terms shall be subject to the exclusive jurisdiction of the courts in Hyderabad, Telangana, India.</p>
                
                <p>All concerns or communications relating to these Terms must be communicated to us using the contact information provided on this website.</p>
            </div>
        </div>
        
        <!-- Privacy Policy -->
        <div id="privacy" class="policy-section" style="background: var(--color-surface-light); border-radius: var(--radius-md); padding: 2rem; margin-bottom: 2rem; border: 1px solid var(--color-surface-lighter);">
            <h2 style="color: var(--color-primary); margin-bottom: 1.5rem;">Privacy Policy</h2>
            
            <div style="color: var(--color-text); line-height: 1.8;">
                <h3 style="color: var(--color-white); margin: 1.5rem 0 1rem;">Introduction</h3>
                <p>This Privacy Policy describes how <strong>Tattva Dental Clinic</strong> and its affiliates (collectively "Tattva Dental Clinic, we, our, us") collect, use, share, protect or otherwise process your information/personal data through our website <strong><?php echo esc_url(home_url('/')); ?></strong> (hereinafter referred to as Platform).</p>
                
                <p>Please note that you may be able to browse certain sections of the Platform without registering with us. We do not offer any product/service under this Platform outside India and your personal data will primarily be stored and processed in India.</p>
                
                <p>By visiting this Platform, providing your information or availing any product/service offered on the Platform, you expressly agree to be bound by the terms and conditions of this Privacy Policy, the Terms of Use and the applicable service/product terms and conditions, and agree to be governed by the laws of India including but not limited to the laws applicable to data protection and privacy. If you do not agree please do not use or access our Platform.</p>
                
                <h3 style="color: var(--color-white); margin: 1.5rem 0 1rem;">Collection</h3>
                <p>We collect your personal data when you use our Platform, services or otherwise interact with us during the course of our relationship and related information provided from time to time. Some of the information that we may collect includes but is not limited to personal data/information provided to us during sign-up/registering or using our Platform such as name, date of birth, address, telephone/mobile number, email ID and/or any such information shared as proof of identity or address.</p>
                
                <p>Some of the sensitive personal data may be collected with your consent, such as your bank account or credit or debit card or other payment instrument information or biometric information such as your facial features or physiological information (in order to enable use of certain features when opted for, available on the Platform) etc all of the above being in accordance with applicable law(s).</p>
                
                <p>You always have the option to not provide information, by choosing not to use a particular service or feature on the Platform. We may track your behaviour, preferences, and other information that you choose to provide on our Platform. This information is compiled and analysed on an aggregated basis.</p>
                
                <p><strong>Important:</strong> If you receive an email, a call from a person/association claiming to be Tattva Dental Clinic seeking any personal data like debit/credit card PIN, net-banking or mobile banking password, we request you to never provide such information. If you have already revealed such information, report it immediately to an appropriate law enforcement agency.</p>
                
                <h3 style="color: var(--color-white); margin: 1.5rem 0 1rem;">Usage</h3>
                <p>We use personal data to provide the services you request. To the extent we use your personal data to market to you, we will provide you the ability to opt-out of such uses. We use your personal data to:</p>
                <ul style="margin-left: 1.5rem; margin-bottom: 1rem;">
                    <li style="margin-bottom: 0.5rem;">Assist in handling and fulfilling appointments and services</li>
                    <li style="margin-bottom: 0.5rem;">Enhance customer experience</li>
                    <li style="margin-bottom: 0.5rem;">Resolve disputes and troubleshoot problems</li>
                    <li style="margin-bottom: 0.5rem;">Inform you about offers, products, services, and updates</li>
                    <li style="margin-bottom: 0.5rem;">Customise your experience</li>
                    <li style="margin-bottom: 0.5rem;">Detect and protect against error, fraud and other criminal activity</li>
                    <li style="margin-bottom: 0.5rem;">Conduct marketing research, analysis and surveys</li>
                </ul>
                
                <h3 style="color: var(--color-white); margin: 1.5rem 0 1rem;">Sharing</h3>
                <p>We may share your personal data internally within our group entities, our other corporate entities, and affiliates to provide you access to the services and products offered by them. These entities and affiliates may market to you as a result of such sharing unless you explicitly opt-out.</p>
                
                <p>We may disclose personal data to third parties such as business partners, third party service providers including logistics partners, prepaid payment instrument issuers, third-party reward programs and other payment opted by you. These disclosures may be required for us to provide you access to our services and products offered to you, to comply with our legal obligations, to enforce our user agreement, to facilitate our marketing and advertising activities, to prevent, detect, mitigate, and investigate fraudulent or illegal activities related to our services.</p>
                
                <h3 style="color: var(--color-white); margin: 1.5rem 0 1rem;">Security Precautions</h3>
                <p>To protect your personal data from unauthorised access or disclosure, loss or misuse we adopt reasonable security practices and procedures. Once your information is in our possession or whenever you access your account information, we adhere to our security guidelines to protect it against unauthorised access and offer the use of a secure server.</p>
                
                <p>However, the transmission of information is not completely secure for reasons beyond our control. By using the Platform, the users accept the security implications of data transmission over the internet and the World Wide Web which cannot always be guaranteed as completely secure, and therefore, there would always remain certain inherent risks regarding use of the Platform. Users are responsible for ensuring the protection of login and password records for their account.</p>
                
                <h3 style="color: var(--color-white); margin: 1.5rem 0 1rem;">Data Deletion and Retention</h3>
                <p>You have an option to delete your account by visiting your profile and settings on our Platform, this action would result in you losing all information related to your account. You may also write to us at the contact information provided below to assist you with these requests.</p>
                
                <p>We retain your personal data information for a period no longer than is required for the purpose for which it was collected or as required under any applicable law. However, we may retain data related to you if we believe it may be necessary to prevent fraud or future abuse or for other legitimate purposes. We may continue to retain your data in anonymised form for analytical and research purposes.</p>
                
                <h3 style="color: var(--color-white); margin: 1.5rem 0 1rem;">Your Rights</h3>
                <p>You may access, rectify, and update your personal data directly through the functionalities provided on the Platform.</p>
                
                <h3 style="color: var(--color-white); margin: 1.5rem 0 1rem;">Consent</h3>
                <p>By visiting our Platform or by providing your information, you consent to the collection, use, storage, disclosure and otherwise processing of your information on the Platform in accordance with this Privacy Policy.</p>
                
                <p>You have an option to withdraw your consent that you have already provided by writing to us at the contact information provided on this website. Please mention "Withdrawal of consent for processing personal data" in your subject line of your communication. However, please note that your withdrawal of consent will not be retrospective and will be in accordance with the Terms of Use, this Privacy Policy, and applicable laws.</p>
                
                <h3 style="color: var(--color-white); margin: 1.5rem 0 1rem;">Changes to this Privacy Policy</h3>
                <p>Please check our Privacy Policy periodically for changes. We may update this Privacy Policy to reflect changes to our information practices. We may alert/notify you about the significant changes to the Privacy Policy, in the manner as may be required under applicable laws.</p>
            </div>
        </div>
        
        <!-- Refund Policy -->
        <div id="refund" class="policy-section" style="background: var(--color-surface-light); border-radius: var(--radius-md); padding: 2rem; margin-bottom: 2rem; border: 1px solid var(--color-surface-lighter);">
            <h2 style="color: var(--color-primary); margin-bottom: 1.5rem;">Refund Policy</h2>
            
            <div style="color: var(--color-text); line-height: 1.8;">
                <p>At Tattva Dental Clinic, we strive to provide the best dental care services. In case of any refund, please note the following:</p>
                
                <div style="background: var(--color-surface); padding: 1.5rem; border-radius: var(--radius-sm); margin: 1.5rem 0; border-left: 4px solid var(--color-primary);">
                    <p style="margin: 0; font-size: 1.1rem;"><strong>Refund Processing Time:</strong> In case of any refund, it will take <strong>5-7 working days</strong> to process and reflect in your account.</p>
                </div>
                
                <h3 style="color: var(--color-white); margin: 1.5rem 0 1rem;">Refund Eligibility</h3>
                <ul style="margin-left: 1.5rem; margin-bottom: 1rem;">
                    <li style="margin-bottom: 0.75rem;">Refunds are applicable for prepaid services that were not availed due to unforeseen circumstances.</li>
                    <li style="margin-bottom: 0.75rem;">Cancellation requests must be made at least 24 hours before the scheduled appointment.</li>
                    <li style="margin-bottom: 0.75rem;">Refund requests should be submitted via email to <a href="mailto:<?php echo esc_attr(get_theme_mod('tattva_email', 'tattvadental.tdc@gmail.com')); ?>" style="color: var(--color-primary);"><?php echo esc_html(get_theme_mod('tattva_email', 'tattvadental.tdc@gmail.com')); ?></a> or by calling us at <a href="tel:<?php echo esc_attr(get_theme_mod('tattva_phone', '08309164387')); ?>" style="color: var(--color-primary);"><?php echo esc_html(get_theme_mod('tattva_phone', '08309164387')); ?></a>.</li>
                </ul>
                
                <h3 style="color: var(--color-white); margin: 1.5rem 0 1rem;">Contact Us</h3>
                <p>For any queries regarding refunds, please contact us:</p>
                <p>
                    <strong>Email:</strong> <a href="mailto:<?php echo esc_attr(get_theme_mod('tattva_email', 'tattvadental.tdc@gmail.com')); ?>" style="color: var(--color-primary);"><?php echo esc_html(get_theme_mod('tattva_email', 'tattvadental.tdc@gmail.com')); ?></a><br>
                    <strong>Phone:</strong> <a href="tel:<?php echo esc_attr(get_theme_mod('tattva_phone', '08309164387')); ?>" style="color: var(--color-primary);"><?php echo esc_html(get_theme_mod('tattva_phone', '08309164387')); ?></a><br>
                    <strong>Address:</strong> <?php echo esc_html(get_theme_mod('tattva_address', 'Tattva Dental Clinic, Uppal, Hyderabad, Telangana 500039, India')); ?>
                </p>
            </div>
        </div>
        
        <div class="text-center" style="margin-top: 2rem;">
            <p style="color: var(--color-gray);">Last Updated: <?php echo date('F Y'); ?></p>
        </div>
    </div>
</section>

<?php get_footer(); ?>

